In [4]:
import torch

In [5]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y


(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [6]:
x = torch.arange(3)
x[1]


tensor(1)

In [7]:
A = torch.arange(144).reshape(12, 12)
A


tensor([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131],
        [132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143]])

In [8]:
B=A.T

In [9]:
A = torch.ones(3, 3)

A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [10]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
A + B

tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])

In [11]:
A = A * B
A = A * A
A = A * A

A = A * A

A = A * A

A = A * A

A = A * A

A

tensor([[0., 1., inf],
        [inf, inf, inf]])

In [12]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()
A

tensor([[0., 1., inf],
        [inf, inf, inf]])

In [13]:
A.numel()

6

In [14]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(inf))

In [15]:
A.shape, A.sum(axis=0), A.sum(axis=1)

(torch.Size([2, 3]), tensor([inf, inf, inf]), tensor([inf, inf]))

Dot Product

In [16]:
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y)


(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [17]:
z = x * y # dot product
z, torch.sum(z)

(tensor([0., 1., 2.]), tensor(3.))

In [18]:
A = torch.arange(12, dtype=torch.float32).reshape(3, 4)
x = torch.arange(4, dtype=torch.float32)

In [22]:
A = torch.ones(3, 4)
B = torch.ones(4, 3)

In [23]:
A @ B

tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])

In [24]:
u = torch.tensor([3.0, -4.0])
torch.norm(u) # L2 norm

tensor(5.)

In [25]:
# L1 norm
torch.abs(u).sum()

tensor(7.)

In [26]:
A = torch.arange(9).reshape(3, 3)
A

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [28]:
# Transpose of a transpose of a matrix is the original matrix
A.T.T, A, 

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]))

In [33]:
B = torch.arange(9).reshape(3, 3)


In [35]:
# To show A.T + B.T = (A + B).T
# A.T, B.T
A.T + B.T, (A + B).T

(tensor([[ 0,  6, 12],
         [ 2,  8, 14],
         [ 4, 10, 16]]),
 tensor([[ 0,  6, 12],
         [ 2,  8, 14],
         [ 4, 10, 16]]))

In [36]:
# Given any square matrix 
# , is 
#  always symmetric? Can you prove the result by using only the results of the previous two exercises?


A = torch.arange(9).reshape(3, 3)
B = A.T

S = A + B
S == S.T


tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [38]:
X = torch.arange(24).reshape(2, 3, 4)
len(X), X.shape

(2, torch.Size([2, 3, 4]))

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[12, 15, 18, 21]],
 
         [[48, 51, 54, 57]]]),
 tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]))