In [2]:
import torch

Let's assume that we are differentiation the function y = 2x.x with respect to column vector x.


In [3]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [4]:
x.requires_grad_(True)
# or x = torch.arange(4.0, requires_grad=True)
'''
What it does is that it tells PyTorch that we plan to calculate the gradient of x during backpropagation.
'''
x.grad  # The default value is None

In [5]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

We can now take the gradient of y with respect to x by calling its backward method. Next, we can access the gradient via x’s grad attribute.

In [6]:
y.backward()

In [7]:
x.grad

tensor([ 0.,  4.,  8., 12.])

Reasoning 

Y = 2.X.X 
Y' = 4.X

In [8]:
x.grad == 4 * x

tensor([True, True, True, True])

In [9]:
# Reseting the gradient
x.grad.zero_()
y = x.sum()

y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [10]:
x.grad.zero_()
y = x * x

# y.backward(gradient=torch.ones(len(y)))
# or
y.sum().backward()
# What it does is that it tells PyTorch that we plan to calculate the gradient of y with respect to x, and the gradient of y is given as an argument in the backward function.
x.grad

tensor([0., 2., 4., 6.])

In [13]:
x = torch.randn(3, requires_grad=True)

In [14]:
x


tensor([ 1.5321, -0.1588,  1.2512], requires_grad=True)

In [15]:
y = x + 2
y

tensor([3.5321, 1.8412, 3.2512], grad_fn=<AddBackward0>)

In [17]:
z = y * y * 2
z

tensor([24.9519,  6.7802, 21.1403], grad_fn=<MulBackward0>)

In [18]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c


In [33]:
a = torch.randn(size=(), requires_grad=True)
a

tensor(0.5955, requires_grad=True)

In [34]:
d = f(a)
d.backward()

In [35]:
a.grad == d / a

tensor(True)

In [40]:
x = torch.tensor(1.0, requires_grad=True)
y = x * 2

In [41]:
y.backward()

In [42]:
print(f'First backward: x.grad = {x.grad}')  # Should print 2.0

First backward: x.grad = 2.0


In [49]:
y = x * 2
y.backward()
print(f'After zeroing gradients: x.grad = {x.grad}')

After zeroing gradients: x.grad = 16.0
