In [1]:
import torch

In [5]:
x = torch.arange(12, dtype=torch.float32)
# Create a tensor with 12 elements ie, Mathematically 1x12 or R^12              
print(x)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])


In [6]:
# Check the number of elements in the tensor
x.numel()

12

In [7]:
# check the shape of the tensor
x.shape # torch.Size([12]) since it is 1D tensor

torch.Size([12])

In [8]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [9]:
X.shape # torch.Size([3, 4]) since it is 2D tensor or matrix of 3x4

torch.Size([3, 4])

In [ ]:
# Alternatively, we can also use the following two lines
X = x.reshape(-1, 4) 
X = x.reshape(3, -1)
# Use it when you know the total number of elements

In [10]:
# All zeros
torch.zeros((2, 3, 4)) # 3D tensor of 2x3x4

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
torch.ones((2, 3, 4)) # 3D tensor of 2x3x4

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [31]:
torch.randn(3, 4) # 2D tensor of 3x4 with random values
# Random values from a normal distribution with mean 0 and variance 1

tensor([[-0.8494, -0.7020, -2.3670,  0.7757],
        [ 1.3339, -2.0039,  1.1883, -0.7752],
        [-0.9649, -0.8707,  0.0743, -0.3083]])

In [32]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [33]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [38]:
print(X)
X[1:3]

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [41]:
print(X)
X[1, 2] = 99
print(X)


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 99.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 99.,  7.],
        [ 8.,  9., 10., 11.]])


Operations

In [47]:
x = torch.arange(12, dtype=torch.float32)
torch.exp(x)

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04])

In [50]:
# natural logarithm
torch.log(torch.exp(x))

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [51]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [55]:
print(x)
x.sum()


tensor([1., 2., 4., 8.])


tensor(15.)

In [56]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [57]:
print(a , "+", b, "=", a + b)

tensor([[0],
        [1],
        [2]]) + tensor([[0, 1]]) = tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [58]:
A = X.numpy()
B = torch.from_numpy(A)

type(A), type(B)

(numpy.ndarray, torch.Tensor)